name: Home
views:
- name: Kitchen
  cards:
  - type: entity-filter
    filter:
    - entity_id: '*kitchen*'
      domain: light
    card_config:
      title: Lights
      
- name: Living Room
  cards:
  - type: entity-filter
    filter:
    - entity_id: '*living_room*'
      domain: light
    card_config:
      title: Lights