- platform: webostv
  host: 192.168.0.68
- platform: group
  name: "Dans Devices"
  services:
    - service: mobile_app_dphone
    - service: mobile_app_dpad
- platform: group
  name: "Phones"
  services:
    - service: mobile_app_dphone
    - service: mobile_app_lphone