# Bathroom
- alias: Bathroom Lights On
  trigger:
    - entity_id: binary_sensor.bathroom_motion
      platform: state
      to: "on"
  condition:
    condition: state
    entity_id: light.bathroom
    state: "off"
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Bathroom
        scene_name: "{{ states.sensor.day_phase.state }}"

- alias: Bathroom Lights Off
  trigger:
    - entity_id: binary_sensor.bathroom_motion
      platform: state
      to: "off"
      for:
        hours: 0
        minutes: 3
        seconds: 0
  action:
    - service: light.turn_off
      entity_id: light.bathroom

- alias: Bathroom Lights Update
  trigger:
    - platform: state
      entity_id: light.bathroom
      to: "on"
    - platform: state
      entity_id: sensor.day_phase
  condition:
    condition: state
    entity_id: light.bathroom
    state: "on"
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Bathroom
        scene_name: "{{ states.sensor.day_phase.state }}"

# Bedroom
- alias: Bedroom Lights Update
  trigger:
    - platform: state
      entity_id: light.bedroom
      to: "on"
    - platform: state
      entity_id: sensor.day_phase
  condition:
    condition: state
    entity_id: light.bedroom
    state: "on"
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Bedroom
        scene_name: "{{ states.sensor.day_phase.state }}"

# Ensuite
- alias: Ensuite Lights Update
  trigger:
    - platform: state
      entity_id: light.ensuite
      to: "on"
    - platform: state
      entity_id: sensor.day_phase
  condition:
    condition: state
    entity_id: light.ensuite
    state: "on"
  action:
    - service: hue.hue_activate_scene
      data_template:
        group_name: Ensuite
        scene_name: "{{ states.sensor.day_phase.state }}"
