# Kitchen
- platform: rest
  resource: !secret hue_kitchen_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Kitchen Light'

- platform: rest
  resource: !secret hue_kitchen_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Kitchen Temperature'

# Living Room
- platform: rest
  resource: !secret hue_living_room_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Living Room Light'

- platform: rest
  resource: !secret hue_living_room_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Living Room Temperature'

# Entrance Hall
- platform: rest
  resource: !secret hue_entrance_hall_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Entrance Hall Light'

- platform: rest
  resource: !secret hue_entrance_hall_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Entrance Hall Temperature'

# Top Floor
- platform: rest
  resource: !secret hue_top_floor_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Top Floor Light'

- platform: rest
  resource: !secret hue_top_floor_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Top Floor Temperature'

# Toilet
- platform: rest
  resource: !secret hue_toilet_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Toilet Light'

- platform: rest
  resource: !secret hue_toilet_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Toilet Temperature'

# Bathroom
- platform: rest
  resource: !secret hue_bathroom_light
  value_template: '{{ value_json.state.lightlevel }}'
  unit_of_measurement: Lux
  name: 'Bathroom Light'

- platform: rest
  resource: !secret hue_bathroom_temperature
  value_template: '{{ value_json.state.temperature | float / 100 }}'
  unit_of_measurement: °C
  name: 'Bathroom Temperature'