- platform: template
  sensors:
    day_phase:
      friendly_name: 'Day Phase'
      value_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=7).replace(minute=0).replace(second=0) and 
            now().isoweekday() <= 5 and 
            states.input_boolean.holiday_mode.state == 'off' %}
            Morning
        {% elif states.sun.sun.state == "above_horizon" or
            now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=12).replace(minute=0).replace(second=0) %}
            Day
        {% elif now() < now().replace(hour=21).replace(minute=45).replace(second=0) and
            now() > now().replace(hour=5).replace(minute=0).replace(second=0) %}
            Evening
        {% else %}
            Night
        {% endif %}
      icon_template: >
        {% if now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=7).replace(minute=0).replace(second=0) and 
            now().isoweekday() <= 5 and 
            states.input_boolean.holiday_mode.state == 'off' %}
            # Morning
            mdi:weather-sunset-up
        {% elif states.sun.sun.state == "above_horizon" or
            now() > now().replace(hour=5).replace(minute=0).replace(second=0) and
            now() < now().replace(hour=12).replace(minute=0).replace(second=0) %}
            # Day
            mdi:weather-sunny
        {% elif now() < now().replace(hour=21).replace(minute=45).replace(second=0) and
            now() > now().replace(hour=5).replace(minute=0).replace(second=0) %}
            # Evening
            mdi:weather-night
        {% else %}
            # Night
            mdi:sleep
        {% endif %}
    lights_on:
        friendly_name: 'Lights On'
        value_template: >
            {{ states.light
                | selectattr('state', 'eq', 'on')
                | rejectattr('attributes.is_hue_group')
                | list | count
            }}
    rooms_on:
        friendly_name: 'Rooms On'
        value_template: >
            {{ states.light
                | selectattr('state', 'eq', 'on')
                | selectattr('attributes.is_hue_group')
                | list | count
            }}
    total_brightness:
        friendly_name: 'Total Brightness'
        value_template: >
            {{ states.light
                | selectattr('state', 'eq', 'on')
                | rejectattr('attributes.is_hue_group')
                | sum(attribute='attributes.brightness')
            }}