- platform: template
  sensors:
    lights_on:
      friendly_name: "Lights On"
      unit_of_measurement: "Count"
      value_template: >
        {{ states.light
            | selectattr('state', 'eq', 'on')
            | rejectattr('attributes.is_hue_group')
            | list 
            | count
        }}
    rooms_on:
      friendly_name: "Rooms On"
      unit_of_measurement: "Count"
      value_template: >
        {{ states.light
            | selectattr('state', 'eq', 'on')
            | selectattr('attributes.is_hue_group')
            | list 
            | count
        }}
    living_room_tv:
      friendly_name: "Living Room TV"
      value_template: >
        {% if states.remote.remote.state == "on" %}
          {{ states.remote.living_room.attributes.current_activity  }}
        {% else %}
          off
        {% endif %}
