- platform: generic_thermostat
  name: Kitchen
  heater: switch.kitchen_heater
  target_sensor: sensor.kitchen_temperature
  min_temp: 10
  max_temp: 23
  target_temp: 12
  tolerance: 0.5
  operation_mode: off
