- platform: template
  switches:
    garage_heaters:
      value_template: {{ is_state('switch.fan_heater', 'on') or is_state('switch.oil_heater', 'on') }}
      turn_on:
        service: scene.turn_on
        data:
          entity_id: scene.garage_heaters_on
      turn_off:
        service: group.turn_on
        data:
          entity_id: scene.garage_heaters_off
