- platform: template
  switches:
    dressing_room_light:
      friendly_name: Dressing Room Light
      value_template: '{{ is_state("light.dressing_room", "on") }}'
      entity_id: light.dressing_room
      turn_on:
        service: hue.hue_activate_scene
        data_template:
          group_name: Dressing Room
          scene_name: '{{ states.sensor.day_phase.state }}'
      turn_off:
        service: light.turn_off
        entity_id: light.dressing_room

    bedroom_light:
      friendly_name: Bedroom Light
      value_template: '{{ is_state("light.bedroom", "on") }}'
      entity_id: light.bedroom
      turn_on:
        service: hue.hue_activate_scene
        data_template:
          group_name: Bedroom
          scene_name: '{{ states.sensor.day_phase.state }}'
      turn_off:
        service: light.turn_off
        entity_id: light.bedroom

    ensuite_light:
      friendly_name: Ensuite Light
      value_template: '{{ is_state("light.ensuite", "on") }}'
      entity_id: light.ensuite
      turn_on:
        service: hue.hue_activate_scene
        data_template:
          group_name: Ensuite
          scene_name: '{{ states.sensor.day_phase.state }}'
      turn_off:
        service: light.turn_off
        entity_id: light.ensuite