- platform: template
  switches:
    brown_noise_on_roam:
      value_template: |
        {{
          is_state("media_player.sonos_roam", "playing") and
          "brown-noise-cold-plunge.mp3" in state_attr("media_player.sonos_roam", "media_content_id")
        }}
      turn_on: 
        service: script.brown_noise_on_roam
      turn_off: 
        service: media_player.media_pause
        target:
          entity_id: media_player.sonos_roam
          