- platform: rest
  resource: https://api.travis-ci.org/repos/danrspencer/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'
