- alias: Everything Off On Nest Away
  trigger:
  - entity_id: climate.house
    platform: state
    from: 'heat'
    to: 'eco'
  action:
  - service: scene.turn_on
    entity_id: scene.everything_off
