- alias: Node Red Watchdog
  trigger:
  - platform: state
    entity_id: input_boolean.node_red_heartbeat
    to: 'off'
    for:
      minutes: 5
  - platform: state
    entity_id: input_boolean.node_red_heartbeat
    to: 'on'
    for:
      minutes: 5
  action:
  - service: hassio.addon_restart
    data:
      addon: a0d7b954_nodered
  - service: notify.ios_dphone
    data:
      message: 'Node-RED has flatlined, restarting...'