- alias: Node Red Watchdog
  trigger:
  - platform: state
    entity_id: input_boolean.node_red_heartbeat
    for:
      minutes: 2
  action:
  - service: hassio.addon_restart
    addon: a0d7b954_nodered
  - service: notify.ios_dphone
    data:
      message: 'Node-RED has flatlined, restarting...'
