- alias: Porch Light On
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
  - service: light.turn_on
    entity_id: light.porch

- alias: Porch Light Off
  trigger:
  - platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'off'
    for:
      hours: 0
      minutes: 5
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.porch