- platform: template
  sensors:
    house_motion:
      friendly_name: 'House Motion'
      value_template: >
        {{ 
          states.binary_sensor.entrance_hall_motion.state == 'on' or
          states.binary_sensor.kitchen_motion.state == 'on' or
          states.binary_sensor.living_room_motion.state == 'on' or
          states.binary_sensor.top_floor_motion.state == 'on' 
        }}

- platform: template
  value_template: '{{ states.sensor.kitchen_motion_sensor.state == 'on' }}'
  name: 'Kitchen Motion'

- platform: rest
  value_template: '{{ states.sensor.living_room_motion_sensor.state == 'on' }}'
  name: 'Living Room Motion'

- platform: rest
  value_template: '{{ states.sensor.entrance_hall_motion_sensor.state == 'on' }}'
  name: 'Entrance Hall Motion'

- platform: rest
  value_template: '{{ states.sensor.top_floor_motion_sensor.state == 'on' }}'
  name: 'Top Floor Motion'
