- platform: rest
  resource: http://192.168.0.44:9006/as/system/information
  method: GET
  name: Living Room SkyQ
  device_class: power
  value_template: "{{ value_json.activeStandby == false }}"

- platform: rest
  resource: http://192.168.0.45:9006/as/system/information
  method: GET
  name: Guest Room SkyQ
  device_class: power
  value_template: "{{ value_json.activeStandby == false }}"
