- platform: template
  sensors:
    occupied:
      friendly_name: "Occupied"
      value_template: >
        {{ 
          states.device_tracker.dphone.state == "home" or
          states.device_tracker.laurens_iphone.state == "home" or
          states.sensor.recent_motion.state|float > 0
        }}

    house_motion:
      friendly_name: "House Motion"
      value_template: >
        {{ 
          states.binary_sensor.entrance_hall_motion_sensor.state == 'on' or
          states.binary_sensor.kitchen_motion_sensor.state == 'on' or
          states.binary_sensor.living_room_motion_sensor.state == 'on' or
          states.binary_sensor.top_floor_motion_sensor.state == 'on' or
          states.binary_sensor.toilet_motion_sensor.state == 'on' or
          states.binary_sensor.bathroom_motion_sensor.state == 'on'
        }}
